source "http://rubygems.org"

gem "rails", "3.0.4"
gem 'mysql'

# gem 'authlogic'
gem 'authlogic', :git => 'git://github.com/binarylogic/authlogic.git'
gem "bcrypt-ruby", :require => "bcrypt"

gem 'muck-engine' #, :path => "~/projects/muck-engine"
gem 'muck-users' #, :path => "~/projects/muck-users"
gem 'muck-auth', :path => '../'

if RUBY_VERSION < '1.9'
  gem "ruby-debug"
end

group :test, :development do
  gem "rspec-rails"
  gem "cucumber-rails"
end

group :test do
  gem "autotest"
  gem "shoulda"
  gem "capybara"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end