# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{muck-auth}
  s.version = "3.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Ball"]
  s.date = %q{2011-02-17}
  s.description = %q{A simple wrapper for the omniauth gem so that it is faster to include oauth in muck based applications.}
  s.email = %q{justin@tatemae.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/muck/authentications_controller.rb",
    "app/helpers/muck_auth_helper.rb",
    "app/views/authentications/_available_services.html.erb",
    "app/views/authentications/_current_services.html.erb",
    "app/views/authentications/failure.html.erb",
    "app/views/authentications/index.html.erb",
    "app/views/authentications/signup.html.erb",
    "config/locales/en.yml",
    "config/routes.rb",
    "db/migrate/20110216045051_create_authentications.rb",
    "lib/muck-auth.rb",
    "lib/muck-auth/config.rb",
    "lib/muck-auth/engine.rb",
    "lib/muck-auth/exceptions.rb",
    "lib/muck-auth/models/authentication.rb",
    "lib/muck-auth/models/user.rb",
    "lib/tasks/muck_auth.rake",
    "muck-auth.gemspec",
    "muck-oauth.gemspec"
  ]
  s.homepage = %q{http://github.com/tatemae/muck-auth}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{OAuth for muck}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<omniauth>, [">= 0"])
      s.add_runtime_dependency(%q<overlord>, [">= 0"])
      s.add_runtime_dependency(%q<muck-engine>, [">= 0"])
      s.add_runtime_dependency(%q<muck-users>, [">= 0"])
      s.add_development_dependency(%q<babelphish>, [">= 0"])
    else
      s.add_dependency(%q<omniauth>, [">= 0"])
      s.add_dependency(%q<overlord>, [">= 0"])
      s.add_dependency(%q<muck-engine>, [">= 0"])
      s.add_dependency(%q<muck-users>, [">= 0"])
      s.add_dependency(%q<babelphish>, [">= 0"])
    end
  else
    s.add_dependency(%q<omniauth>, [">= 0"])
    s.add_dependency(%q<overlord>, [">= 0"])
    s.add_dependency(%q<muck-engine>, [">= 0"])
    s.add_dependency(%q<muck-users>, [">= 0"])
    s.add_dependency(%q<babelphish>, [">= 0"])
  end
end

